// Madinah mushaf page layout (public/data/mushaf.json, generated by scripts/fetch-mushaf.mjs).
// It holds only line breaks as word ranges; the words themselves come from the bundled text.

/** ["h", surah] header · ["b", surah] basmala · [[surah, ayah, fromToken, toToken], ...] text line */
export type MushafLine = ['h', number] | ['b', number] | [number, number, number, number][];

export interface MushafPage {
  juz: number;
  lines: MushafLine[];
}

export const PAGE_COUNT = 604;

export interface Mushaf {
  pages: MushafPage[];
  /** Page holding the first word of surah:ayah. */
  pageOf(surah: number, ayah: number): number;
  /** Page holding the surah's header (may precede the page of ayah 1). */
  surahStartPage(surah: number): number;
}

let cached: Promise<Mushaf> | null = null;

export function loadMushaf(): Promise<Mushaf> {
  cached ??= fetch(`${import.meta.env.BASE_URL}data/mushaf.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`Could not load mushaf layout (HTTP ${r.status})`);
      return r.json() as Promise<{ pages: MushafPage[] }>;
    })
    .then(({ pages }) => {
      const first = new Map<string, number>();
      const header = new Map<number, number>();
      pages.forEach((pg, i) => {
        for (const line of pg.lines) {
          if (line[0] === 'h') header.set(line[1] as number, i + 1);
          else if (line[0] !== 'b') {
            for (const [s, a] of line as [number, number, number, number][]) {
              const k = `${s}:${a}`;
              if (!first.has(k)) first.set(k, i + 1);
            }
          }
        }
      });
      return {
        pages,
        pageOf: (s, a) => first.get(`${s}:${a}`) ?? 1,
        surahStartPage: (s) => header.get(s) ?? first.get(`${s}:1`) ?? 1,
      };
    });
  cached.catch(() => (cached = null));
  return cached;
}
