// Madinah mushaf pages (public/data/mushaf.json, generated by scripts/fetch-mushaf.mjs): the King Fahd
// Complex QCF V2 layout. Each text line lists, per ayah, the words as glyph codes of that page's font
// (public/fonts/qcf-v2/p{page}.woff2). The words' text is verified against the bundled Quran text.

/** ["h", surah] header · ["b", surah] basmala · [[surah, ayah, "glyph glyph …"], ...] text line */
export type MushafLine = ['h', number] | ['b', number] | [number, number, string][];

export interface MushafPage {
  juz: number;
  lines: MushafLine[];
}

export const PAGE_COUNT = 604;

export interface Mushaf {
  pages: MushafPage[];
  /** Page holding the first word of surah:ayah. */
  pageOf(surah: number, ayah: number): number;
  /** Page holding the surah's header (may precede the page of ayah 1). */
  surahStartPage(surah: number): number;
  /** Page holding word `pos` (1-based Quran.com word position, as in QDC timings) of surah:ayah. */
  wordPage(surah: number, ayah: number, pos: number): number;
  /** 1-based position within its ayah of the first word of each text segment, keyed by the segment. */
  segStart: WeakMap<[number, number, string], number>;
}

let cached: Promise<Mushaf> | null = null;

export function loadMushaf(): Promise<Mushaf> {
  cached ??= fetch(`${import.meta.env.BASE_URL}data/mushaf.json?v=${__DATA_VERSION__}`)
    .then((r) => {
      if (!r.ok) throw new Error(`Could not load mushaf layout (HTTP ${r.status})`);
      return r.json() as Promise<{ pages: MushafPage[] }>;
    })
    .then(({ pages }) => {
      const sample = pages[2]?.lines.find((l) => l[0] !== 'h' && l[0] !== 'b') as [number, number, string][] | undefined;
      if (typeof sample?.[0]?.[2] !== 'string') throw new Error('Mushaf data is out of date — please reload the page');
      const first = new Map<string, number>();
      const header = new Map<number, number>();
      const count = new Map<string, number>(); // words of each ayah seen so far
      const breaks = new Map<string, [number, number][]>(); // per ayah: [first word position, page] where it continues
      const segStart = new WeakMap<[number, number, string], number>();
      pages.forEach((pg, i) => {
        for (const line of pg.lines) {
          if (line[0] === 'h') header.set(line[1] as number, i + 1);
          else if (line[0] !== 'b') {
            for (const seg of line as [number, number, string][]) {
              const k = `${seg[0]}:${seg[1]}`;
              if (!first.has(k)) first.set(k, i + 1);
              const start = (count.get(k) ?? 0) + 1;
              segStart.set(seg, start);
              count.set(k, start - 1 + seg[2].split(' ').length);
              const b = breaks.get(k) ?? [];
              if (b[b.length - 1]?.[1] !== i + 1) b.push([start, i + 1]);
              breaks.set(k, b);
            }
          }
        }
      });
      return {
        pages,
        pageOf: (s, a) => first.get(`${s}:${a}`) ?? 1,
        surahStartPage: (s) => header.get(s) ?? first.get(`${s}:1`) ?? 1,
        wordPage: (s, a, pos) => {
          const b = breaks.get(`${s}:${a}`);
          if (!b) return 1;
          let p = b[0][1];
          for (const [start, page] of b) if (pos >= start) p = page;
          return p;
        },
        segStart,
      };
    });
  cached.catch(() => (cached = null));
  return cached;
}

const fonts = new Map<number, Promise<void>>();

/** Load the QCF V2 font for a page (family "qcf-p{page}"). */
export function loadPageFont(page: number): Promise<void> {
  if (!fonts.has(page)) {
    const face = new FontFace(`qcf-p${page}`, `url(${import.meta.env.BASE_URL}fonts/qcf-v2/p${page}.woff2)`, { display: 'block' });
    const p = face.load().then((f) => void document.fonts.add(f));
    p.catch(() => fonts.delete(page));
    fonts.set(page, p);
  }
  return fonts.get(page)!;
}
