// Access to the bundled Quran data (public/data/, generated by scripts/fetch-data.mjs).
// Text is returned exactly as stored — never modify it.

export interface SurahMeta {
  n: number;
  ar: string;
  en: string;
  tr: string;
  ayahs: number;
  start: number; // global ayah number of ayah 1 is start + 1
  type: string;
}

const base = import.meta.env.BASE_URL;
const cache = new Map<string, Promise<unknown>>();

function load<T>(file: string): Promise<T> {
  if (!cache.has(file)) {
    const p = fetch(`${base}data/${file}`).then((r) => {
      if (!r.ok) throw new Error(`Could not load ${file} (HTTP ${r.status})`);
      return r.json();
    });
    p.catch(() => cache.delete(file));
    cache.set(file, p);
  }
  return cache.get(file) as Promise<T>;
}

export const loadMeta = () => load<SurahMeta[]>('meta.json');

export async function surahText(n: number): Promise<string[]> {
  const d = await load<{ surahs: string[][] }>('quran-uthmani.json');
  return d.surahs[n - 1];
}

export async function surahTranslation(n: number): Promise<string[]> {
  const d = await load<{ surahs: string[][] }>('en-sahih.json');
  return d.surahs[n - 1];
}

export async function surahMeta(n: number): Promise<SurahMeta> {
  const meta = await loadMeta();
  const s = meta[n - 1];
  if (!s) throw new Error(`No surah ${n}`);
  return s;
}

export const globalAyahNumber = (s: SurahMeta, ayah: number) => s.start + ayah;

export const reference = (s: SurahMeta, from: number, to = from) =>
  `${s.en} · ${s.n}:${from}${to > from ? `–${to}` : ''}`;
