// Access to the bundled Quran data (public/data/, generated by scripts/fetch-data.mjs).
// Text is returned exactly as stored — never modify it.

export interface SurahMeta {
  n: number;
  ar: string;
  en: string;
  tr: string;
  ayahs: number;
  start: number; // global ayah number of ayah 1 is start + 1
  type: string;
}

import { currentTranslation, translationFile } from './translations';

const base = import.meta.env.BASE_URL;
const cache = new Map<string, Promise<unknown>>();

function load<T>(file: string): Promise<T> {
  if (!cache.has(file)) {
    // Versioned URL: after an update, new code never gets a stale cached copy of old data.
    const p = fetch(`${base}data/${file}?v=${__DATA_VERSION__}`).then((r) => {
      if (!r.ok) throw new Error(`Could not load ${file} (HTTP ${r.status})`);
      return r.json();
    });
    p.catch(() => cache.delete(file));
    cache.set(file, p);
  }
  return cache.get(file) as Promise<T>;
}

export const loadMeta = () => load<SurahMeta[]>('meta.json');

export async function surahText(n: number): Promise<string[]> {
  const d = await load<{ surahs: string[][] }>('quran-uthmani.json');
  return d.surahs[n - 1];
}

/** The translation of a surah, per ayah: the chosen one (src/data/translations.ts) unless `id` is given. */
export async function surahTranslation(n: number, id = currentTranslation()): Promise<string[]> {
  const d = await load<{ surahs: string[][] }>(translationFile(id));
  return d.surahs[n - 1];
}

export async function surahMeta(n: number): Promise<SurahMeta> {
  const meta = await loadMeta();
  const s = meta[n - 1];
  if (!s) throw new Error(`No surah ${n}`);
  return s;
}

export const globalAyahNumber = (s: SurahMeta, ayah: number) => s.start + ayah;

export const reference = (s: SurahMeta, from: number, to = from) =>
  `${s.en} · ${s.n}:${from}${to > from ? `–${to}` : ''}`;

/** Quran.com word positions (QDC segment indices) → our word indices, where they differ (word-map.json). */
export const loadWordMap = () => load<{ map: Record<string, string> }>('word-map.json').then((d) => d.map);

/** Quran.com English word-by-word meanings, "a|b|…" per Quran.com word position (en-wbw.json). */
export async function surahWordMeanings(n: number): Promise<string[]> {
  const d = await load<{ surahs: string[][] }>('en-wbw.json');
  return d.surahs[n - 1];
}
